# Generated by Django 5.0.3 on 2024-04-08 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Escola', '0002_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='id_turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Escola.turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='id_professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Escola.professor'),
        ),
    ]
